name: "Newman Tests"
on: [push, pull_request] 
jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: postman/newman
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Run API Tests
        run: newman run "Restful Booker BVT.postman_collection.json" -e Production.postman_environment.json
